accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import accviews
from django.urls import reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    path('signup/', accviews.SignUp.as_view(), name='signup'),
    path('<int:pk>/personal/', accviews.personal, name='personal'),
    path('<int:pk>/edit_accounts/', accviews.edit_account, name='edit-account'),
    
    path('<int:pk>/change_password/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change_form.html',success_url=reverse_lazy('accounts:change-password-done')), name='change-password'),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), name='change-password-done'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_form.html',success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_complete'),

    # path('reset_password/', auth_views.PasswordResetView.as_view(), name='reset_password'),
    # path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

dashboard/urls.py
from django.urls import path
from .dashboardviews import dashboard, overview, preprocessing, processing, validation, visualization, profile, edit_profile

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('<int:pk>/profile/',profile,  name='profile'),
    path('<int:pk>/edit_profile/',edit_profile,  name='edit_profile'),  
    path('overview/',overview,  name='overview'),
    path('preprocessing/',preprocessing,  name='preprocessing'),
    path('processing/',processing,  name='processing'),
    path('validation/',validation,  name='validation'),
    path('visualization/',visualization,  name='visualization'),


    # path('<int:pk>/update/',UserUpdateView.as_view(template_name='dashboard/user_update.html'), name='user_update'),
    # path('files/upload/', dashboardviews.file_upload,  name='file_upload'),
    # path('files/upload/<int:pk>', dashboardviews.delete_file, name='delete_file'),
    
]

landing_page/urls.py
from django.urls import path
from .views import tutorial, product, contact, landing_page, aboutus, newsletter, privacy, terms

app_name = 'landing_page'

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('product/', product, name='product'),
    path('contact/', contact, name='contact'),
    path('about-us/', aboutus, name='about-us'),
    path('tutorials/', tutorial, name='tutorial' ),
    path('privacy_policy/', privacy, name='privacy-policy' ),
    path('terms_of_service/', terms, name='terms-of-service' ),
    # path('news_letter/', newsletter, name='news-letter' ),
    

]

mvp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from landing_page import views
from landing_page.views import HomePage
from accounts import accviews


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomePage,name='home'),
    path('landing_page/', include('landing_page.urls', namespace='landing_page')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib import auth
from django.contrib.auth import get_user_model
from django_countries.fields import CountryField
# Create your models here.

class User(auth.models.User,auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)


class UserProfile(models.Model):
    
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, blank=True)
    company_name = models.CharField(max_length=50, blank=True)
    country = CountryField(null=True)
    
    AFF_CHOICES = (('Academic','Academic'),
                    ('Bussiness','Bussiness'),
                    ('Non-profit','Non-profit'),
                    ('Industry/Government','Industry/Government'))

    affiliation = models.CharField(max_length=50, choices=AFF_CHOICES, null=True, blank=True)

    def __str__(self):
        return str(self.user)

accounts/templates/accounts/login.html
{% load static %} {% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'landing_page/css/landingpage.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <title>Login - Eddies</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'landing_page/images/eddieslogo.png' %}">
    <!-- AOS -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
</head>

<body style="background:  #efeff0">
    {% include 'dashboard/messages.html' %}
    <div class="container" data-aos="fade-in" data-aos-duration="1000">
        <div class="box-login">
            <div class="login-icon">
                <a href="{% url 'home' %}"><img width="200" height="200" src="{% static 'landing_page/images/eddieslogo.png' %}"></a>
            </div>
            <h1 style="text-align: center;">Welcome!</h1>
            <form method="POST">
                {% csrf_token %} {% bootstrap_form form %}
                <input type="submit" class='btn btn-dark ' value="Login" style="margin-top: 20px; position: absolute; right: 30px; bottom:20px; padding-left: 30px; padding-right: 30px;" ">
            </form>
            <h6>Don't have account yet?
                <a href="{% url 'accounts:signup' %} ">Sign Up </a></h6>
            <hr>
            <h6><a href="{% url 'accounts:password_reset' %} ">Forgot Password</a></h5>

        </div>

    </div>
    <script src="{% static 'landing_page/js/jquery.min.js' %} "></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js " integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0 " crossorigin="anonymous "></script>
    <script>
        setTimeout(function() {
            if ($('#msg').length > 0) {
                $('#msg').remove();
            }
        }, 4000)
    </script>
    <!-- AOS -->
    <script src="https://unpkg.com/aos@next/dist/aos.js "></script>
    <script>
        AOS.init();
    </script>

</body>


</html>

accounts/templates/accounts/mail_template.html
{% load static %}
<html>
    <body>
        <div><h2>Hello, <span style="color:blue;">{{ first_name }} {{last_name}}</span> !</h2></div>
        <br>
        <div><p><strong>Thank you for joining Us.</strong></p></div>
        <div><p>We are very glad you accepted the offer to become an early adopters of our Eddies MVP.</p></div>
        <div><p>Feedbacks and suggestion regarding our products are needed for future product development.</p></div>
        <div><p>Please submit any of it to: eddies.startup@gmail.com</p>
        <br>
        <div><p><strong>Best regards,</strong></p></div>
        <div><p>Eddies Team</p></div>
        <div><p>eddies.startup@gmail.com</p></div>   
    </body>
</html>

accounts/templates/accounts/password_change_done.html
{% load static %}{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'landing_page/css/landingpage.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <title>Success - Eddies</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'landing_page/images/eddieslogo.png' %}">
    <!-- AOS -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-L4DPXZLM71"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-L4DPXZLM71');
    </script>
</head>

<body style="background: #efeff0;">
    <section id="float-form">
        <div class="container">
            <div class="box-float">
                <div class="row">
                    <div class="col-md-12">
                        <div class="box-password-change" data-aos="zoom-in" data-aos-duration="1000">
                            <h1 style="text-align: center;">Password Succsessfully Changed.</h1>
                            <br>
                            <br>
                            <img width="600" height="300" src="{% static 'landing_page/images/passwordchange.svg' %}">
                            <h4>Back to <a href="{% url 'dashboard:profile' request.user.id %}">My Profile</a></h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>

    <!-- AOS -->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>

</html>

accounts/templates/accounts/password_change_form.html
{% load static %}{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'landing_page/css/landingpage.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <title>Registration - Eddies</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'landing_page/images/eddieslogo.png' %}">
    <!-- AOS -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-L4DPXZLM71"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-L4DPXZLM71');
    </script>

</head>

<body style="background: #efeff0;">
    <section id="float-form">
        <div class="container">
            <div class="box-float">
                <h1 style="text-align: center; padding-top:20px; padding-bottom:20px; font-size: 3rem;">Change Password</h1>
                <hr>
                <div class="row">
                    <div class="col-md-6">
                        <div class="box-signup" data-aos="fade-in" data-aos-duration="1000">

                            <form method="POST">
                                {% csrf_token %} {% bootstrap_form form %}
                                <br>
                                <input type="submit" class='btn btn-primary' value="Change Password">
                            </form>

                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="box-image" data-aos="fade-in" data-aos-duration="1000">
                            <a href="{% url 'dashboard:profile' request.user.id %}"><img src="{% static 'landing_page/images/eddieslogo.jpg' %}" alt="crash" style="width: 100%; height:100%"> </a>
                            <h3 style="text-align:center;">Back to <a href="{% url 'dashboard:profile' request.user.id %}">{{user.username}}</a> profile.</h3>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
    <!-- AOS -->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>
</body>

</html>

accounts/templates/accounts/password_reset.html
{% load static %}{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'landing_page/css/landingpage.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <title>Registration - Eddies</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'landing_page/images/eddieslogo.png' %}">
    <!-- AOS -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-L4DPXZLM71"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-L4DPXZLM71');
    </script>

</head>

<body style="background: #efeff0;">
    <section id="float-form">
        <div class="container">
            <div class="box-float-password">
                <h1 style="text-align: center; padding-top:20px; padding-bottom:20px; font-size: 3rem;">Reset Password</h1>
                <hr>

                <div class="row">
                    <div class="col-md-6">
                        <div class="box-signup" data-aos="fade-in" data-aos-duration="1000">
                            <h4 style="font-weight: 400;">Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</h4>
                            <form method="POST">
                                {% csrf_token %} {% bootstrap_form form %}
                                <br>
                                <input type="submit" class='btn btn-primary' value="Change Password">
                            </form>

                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="box-image" data-aos="fade-in" data-aos-duration="1000">
                            <a href="{% url 'home' %}"><img src="{% static 'landing_page/images/eddieslogo.jpg' %}" alt="crash" style="width: 100%; height:100%"> </a>
                            <h3 style="text-align:center;">Back to
                                <a href="{% url 'accounts:login' %}">Login</a>
                            </h3>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
    <!-- AOS -->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>
</body>

</html>

accounts/templates/accounts/password_reset_done.html
{% load static %}{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'landing_page/css/landingpage.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <title>Success - Eddies</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'landing_page/images/eddieslogo.png' %}">
    <!-- AOS -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-L4DPXZLM71"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-L4DPXZLM71');
    </script>
</head>

<body style="background: #efeff0;">
    <section id="float-form">
        <div class="container">
            <div class="box-float">
                <div class="row">
                    <div class="col-md-12">
                        <div class="box-password-change" data-aos="zoom-in" data-aos-duration="1000">
                            <h1 style="text-align: center;">Password Succsessfully Changed.</h1>
                            <br>
                            <br>
                            <img width="600" height="300" src="{% static 'landing_page/images/passwordchange.svg' %}">
                            <h4>Back to <a href="{% url 'accounts:login' %}">Login</a></h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>

    <!-- AOS -->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>

</html>

accounts/templates/accounts/password_reset_form.html
{% load static %}{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'landing_page/css/landingpage.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <title>New Password - Eddies</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'landing_page/images/eddieslogo.png' %}">
    <!-- AOS -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-L4DPXZLM71"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-L4DPXZLM71');
    </script>

</head>

<body style="background: #efeff0;">
    <section id="float-form">
        <div class="container">
            <div class="box-float-password">
                <h1 style="text-align: center; padding-top:20px; padding-bottom:20px; font-size: 3rem;">New Password</h1>
                <hr>
                <div class="row">
                    <div class="col-md-6">
                        <div class="box-signup" data-aos="fade-in" data-aos-duration="1000">

                            <form method="POST">
                                {% csrf_token %} {% bootstrap_form form %}
                                <br>
                                <input type="submit" class='btn btn-primary' value="Change Password">
                            </form>

                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="box-image" data-aos="fade-in" data-aos-duration="1000">
                            <a href="{% url 'home' %}"><img src="{% static 'landing_page/images/eddieslogo.jpg' %}" alt="crash" style="width: 100%; height:100%"> </a>
                            <h3 style="text-align:center;">Back to
                                <a href="{% url 'accounts:login' %}">Login</a></h3>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
    <!-- AOS -->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>
</body>

</html>

accounts/templates/accounts/signup.html
{% load static %}{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'landing_page/css/landingpage.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <title>Registration - Eddies</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'landing_page/images/eddieslogo.png' %}">
    <!-- AOS -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-L4DPXZLM71"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-L4DPXZLM71');
    </script>
</head>

<body style="background: #efeff0;">
    <section id="float-form">
        <div class="container">
            <div class="box-float" data-aos="fade-in" data-aos-duration="1000">
                <div class="row">
                    <div class="col-md-6">
                        <div class="box-signup">
                            <h1 style="text-align: center;">Join Us Now!</h1>
                            <hr>
                            <form method="POST">
                                {% csrf_token %} {% bootstrap_form form %}

                                <input type="submit" class='btn btn-primary' value="Sign Up">
                            </form>
                            <br>
                            <p>By signing up you agree to Eddies <a href="{% url 'landing_page:terms-of-service' %}">Terms of Service</a> and <a href="{% url 'landing_page:privacy-policy' %}">Privacy Policy.</a> </p>

                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="box-image-signup">
                            <a href="{% url 'home' %}"><img src="{% static 'landing_page/images/eddieslogo.jpg' %}" alt="crash" style="width: 100%; height:100%"></a>
                            <h3 style="text-align: center;"><a href=" {% url 'accounts:login' %} ">Sign in</a> or back to <a href="{% url 'home' %}">Home</a>.</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
    <!-- AOS -->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>

</html>