accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import accviews
from django.urls import reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    path('signup/', accviews.SignUp.as_view(), name='signup'),
    path('<int:pk>/personal/', accviews.personal, name='personal'),
    path('<int:pk>/edit_accounts/', accviews.edit_account, name='edit-account'),
    
    path('<int:pk>/change_password/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change_form.html',success_url=reverse_lazy('accounts:change-password-done')), name='change-password'),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), name='change-password-done'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_form.html',success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_complete'),

    # path('reset_password/', auth_views.PasswordResetView.as_view(), name='reset_password'),
    # path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

dashboard/urls.py
from django.urls import path
from .dashboardviews import dashboard, overview, preprocessing, processing, validation, visualization, profile, edit_profile

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('<int:pk>/profile/',profile,  name='profile'),
    path('<int:pk>/edit_profile/',edit_profile,  name='edit_profile'),  
    path('overview/',overview,  name='overview'),
    path('preprocessing/',preprocessing,  name='preprocessing'),
    path('processing/',processing,  name='processing'),
    path('validation/',validation,  name='validation'),
    path('visualization/',visualization,  name='visualization'),


    # path('<int:pk>/update/',UserUpdateView.as_view(template_name='dashboard/user_update.html'), name='user_update'),
    # path('files/upload/', dashboardviews.file_upload,  name='file_upload'),
    # path('files/upload/<int:pk>', dashboardviews.delete_file, name='delete_file'),
    
]

landing_page/urls.py
from django.urls import path
from .views import tutorial, product, contact, landing_page, aboutus, newsletter, privacy, terms

app_name = 'landing_page'

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('product/', product, name='product'),
    path('contact/', contact, name='contact'),
    path('about-us/', aboutus, name='about-us'),
    path('tutorials/', tutorial, name='tutorial' ),
    path('privacy_policy/', privacy, name='privacy-policy' ),
    path('terms_of_service/', terms, name='terms-of-service' ),
    # path('news_letter/', newsletter, name='news-letter' ),
    

]

mvp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from landing_page import views
from landing_page.views import HomePage
from accounts import accviews


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomePage,name='home'),
    path('landing_page/', include('landing_page.urls', namespace='landing_page')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone


User = get_user_model()

# Create your models here.
class forfile(models.Model):
    file_name = models.CharField(max_length=200)
    file_link = models.FileField(upload_to='file_list/')
    created = models.DateTimeField(editable=False, null=True)
    modified = models.DateTimeField(null=True)
    user = models.ForeignKey(
        get_user_model(), related_name='users',
        on_delete=models.CASCADE, null=True
    )

    def save (self, *args, **kwargs ):
        if not self.id:
            self.created = timezone.now()
        self.modified = timezone.now()
        return super(forfile, self).save(*args, **kwargs)


    def __str__(self):
        return self.file_name
    
    def delete(self, *args, **kwargs):
        self.file_link.delete()
        super().delete(*args, **kwargs)

dashboard/forms.py
from django import forms
from .models import forfile

class forfileform(forms.ModelForm):
    class Meta:
        model = forfile
        fields = ('file_name','file_link')
        exclude = ('user',)

        widgets = {
            'file_name' : forms.TextInput(attrs={'id': 'name-field', 'placeholder': 'Enter file name'}),
            'file_link' : forms.FileInput(attrs={'id': 'link-field', 'placeholder': 'Enter file name'}),
        }

dashboard/templates/dashboard/basedashboard.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eddies</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'landing_page/images/eddieslogo.png' %}">
    <!-- AOS -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'landing_page/css/landingpage.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-L4DPXZLM71"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-L4DPXZLM71');
    </script>
    <!-- Slider -->
</head>

<body style="background-color: rgb(243, 239, 239)">
    <!--- Navigation Bar -->
    <section id="Navbar">
        <nav class="navbar navbar-expand-lg bgcolor navbar-custom">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'landing_page/images/eddieslogo.jpg' %}" alt="logo picture" width="180px" height="auto"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-bars"></i>
                    </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav testi">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'home' %}#">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" aria-haspopup="true">
                            Settings
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item drop" href="{% url 'accounts:edit-account' request.user.id %}">Account Settings</a>
                                <a class="dropdown-item drop" href="{% url 'accounts:change-password' request.user.id %}">Change Password</a>
                                <a class="dropdown-item drop" href="{% url 'landing_page:privacy-policy'  %}">Privacy Policy</a>
                                <a class="dropdown-item drop" href="{% url 'landing_page:terms-of-service'  %}">Terms of Service</a>
                            </div>
                        </li>
                    </ul>

                    {% if user.is_authenticated %}
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mynavbar">
                            <a class="nav-link" href="{% url  'dashboard:profile' request.user.id %}">Hello <span style="color:#4460EF;">{{ user.username }} </span>!</a>
                        </li>
                        <li class="nav-item mynavbar">
                            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                    </ul>
                    {% else %}
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mynavbar">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                        </li>
                        <li class="nav-item ">
                            <a class="btnnav" href="{% url 'accounts:signup' %}"><button type="button">Sign Up</button></a>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </nav>
    </section>


    {% block content %}{% endblock %}



    <!--- Bottom headline  -->
    <!-- JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="{% static 'landing_page/js/jquery.min.js' %}"></script>
    <script src="{% static 'landing_page/js/bootstrap.bundle.min.js' %}"></script>
    <script>
        $(window).scroll(function() {
            $('nav').toggleClass('scrolled', $(this).scrollTop() > 200);
        });
        setTimeout(function() {
            if ($('#msg').length > 0) {
                $('#msg').remove();
            }
        }, 4000);
        setTimeout(function() {
            $('.loader_bg').fadeToggle();
        }, 500);
        $(document).ready(function() {
            $('ul.navbar-nav > li')
                .click(function(e) {
                    $('ul.navbar-nav > li')
                        .removeClass('active');
                    $(this).addClass('active');
                });
        });
    </script>
    <!-- AOS -->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>

</body>

</html>

dashboard/templates/dashboard/baseproduct.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap core JavaScript -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- <script src="{% static 'landing_page/js/jquery.min.js' %}"></script> -->

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'landing_page/css/landingpage.css' %}">
    <link rel="stylesheet" href="{% static 'landing_page/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'landing_page/css/simple-sidebar.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">
    <!-- Custom styles for this template -->

    <title>Eddies - Dashboard</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'landing_page/images/eddieslogo.png' %}">
    <!-- AOS -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">



</head>

<body style="background-color: rgb(243, 239, 239)">



    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">
                <a href="{% url 'home' %}"><img src="{% static 'landing_page/images/eddieslogo.jpg' %}" alt="crash" style="width:180px; height:100% ;"></a>
            </div>
            <div class="list-group list-group-flush">
                <a href="{% url 'dashboard:overview' %}" class="list-group-item list-group-item-action">Overview</a>
                <a href="{% url 'dashboard:preprocessing' %}" class="list-group-item list-group-item-action">Preprocessing</a>
                <a href="{% url 'dashboard:processing' %}" class="list-group-item list-group-item-action">Processing</a>
                <a href="{% url 'dashboard:visualization' %}" class="list-group-item list-group-item-action">Data Visualization</a>
                <a href="{% url 'dashboard:validation' %}" class="list-group-item list-group-item-action">Data Validation</a>
            </div>

        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">

            <nav class="navbar navbar-expand-lg border-bottom">
                <button id="menu-toggle"><i class="fas fa-angle-double-left fa-lg"></i></button>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    {% if user.is_authenticated %}
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:personal' request.user.id %}" style="color:blue; font-weight: bold;">{{user.username}}</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              Settings
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item drop" href="{% url 'accounts:change-password' request.user.id %}">Change Password</a>
                                <a class="dropdown-item drop" href="{% url 'accounts:edit-account' request.user.id %}">Edit Accounts</a>
                                <a class="dropdown-item drop" href="{% url 'landing_page:privacy-policy'  %}">Privacy Policy</a>
                                <a class="dropdown-item drop" href="{% url 'landing_page:terms-of-service'  %}">Terms of Service</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </nav>

            <div class="container-fluid">
                {% include 'dashboard/messages.html' %} {% block content %} {% endblock %}
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script> -->

    <!-- <script src="{% static 'landing_page/js/bootstrap.bundle.min.js' %}"></script> -->
    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
    <!-- Menu Toggle Script -->
    <script>
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });

        $(document).on('click', 'a', function() {
            $(this).addClass('list-group-item').siblings.removeClass('list-group-item')
        });

        setTimeout(function() {
            if ($('#msg').length > 0) {
                $('#msg').remove();
            }
        }, 4000);
    </script>
    <!-- AOS -->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>

</body>

</html>

dashboard/templates/dashboard/form_field.html
{% load widget_tweaks %}

<small>{{field.label_tag}}</small> {% if form.is_bound %} {% if field.errors or form.non_field_errors %}
<div class="invalid-feedback">
    {{ form.non_field_errors}} {{ field.errors }}
</div>
{% else %} {% render_field field class="form-control is-valid" %} {% endif %} {% else %} {% with "form-control input-field-"|add:field.name as field_class %}{% render_field field class=field_class %}{% endwith %} {% endif %}

dashboard/templates/dashboard/home.html
{% extends 'dashboard/basedashboard.html' %} {% load static %} {% block content %}
<div class="loader_bg">
    <div class="loader"></div>
</div>
<div class="container" data-aos="fade-in" data-aos-duration="1000">
    <br>
    <br>
    <h1 style="text-align:center">Congratulations, <span style="color:blue;">{{user.username}}</span>.</h1>
    <hr>
    <h4 style="text-align:center">Go to your profile to get your visual-interactive data on Eddies Analytics.</h4>
    <center>
        <a href="{% url 'dashboard:profile' request.user.id %}" class="btn btn-dark" style="margin-left:20px; margin-top:20px;">My Profile</a>

    </center>
    <div class="dashboard-home">
        <img width="50%" height="auto" src="{% static 'landing_page/images/one_step.svg' %}">
    </div>

</div>



{% endblock %}

dashboard/templates/dashboard/messages.html
{% if messages %} {% for message in messages %}
<div class="alert {{message.tags}} m-2" id="msg" role="alert">
    {{ message }}
</div>
{% endfor %} {% endif %}

dashboard/templates/dashboard/overview.html
{% extends 'dashboard/baseproduct.html' %} {% load static %} {% block content %} {% load static %}{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Success - Eddies</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'landing_page/images/eddieslogo.png' %}">
    <!-- AOS -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
</head>

<body style="background: #efeff0;">
    <section id="float-form">
        <div class="container">
            <div class="box-float">
                <div class="row">
                    <div class="col-md-12">
                        <div class="box-password-change" data-aos="zoom-in" data-aos-duration="1000">
                            <h1 style="text-align: center;">Coming Soon.</h1>
                            <br>
                            <br>
                            <img width="600" height="300" src="{% static 'landing_page/images/passwordchange.svg' %}">
                            <h4>Back to <a href="{% url 'dashboard:dashboard' %}">Home</a></h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>

    <!-- AOS -->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>

</html>




{% endblock %}

dashboard/templates/dashboard/preprocessing.html
{% extends 'dashboard/baseproduct.html' %} {% load static %} {% block content %} {% load static %}{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Success - Eddies</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'landing_page/images/eddieslogo.png' %}">
    <!-- AOS -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
</head>

<body style="background: #efeff0;">
    <section id="float-form">
        <div class="container">
            <div class="box-float">
                <div class="row">
                    <div class="col-md-12">
                        <div class="box-password-change" data-aos="zoom-in" data-aos-duration="1000">
                            <h1 style="text-align: center;">Coming Soon.</h1>
                            <br>
                            <br>
                            <img width="600" height="300" src="{% static 'landing_page/images/passwordchange.svg' %}">
                            <h4>Back to <a href="{% url 'dashboard:dashboard' %}">Home</a></h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>

    <!-- AOS -->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>

</html>


{% endblock %}

dashboard/templates/dashboard/processing.html
{% extends 'dashboard/baseproduct.html' %} {% load static %} {% block content %} {% load static %}{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Success - Eddies</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'landing_page/images/eddieslogo.png' %}">
    <!-- AOS -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
</head>

<body style="background: #efeff0;">
    <section id="float-form">
        <div class="container">
            <div class="box-float">
                <div class="row">
                    <div class="col-md-12">
                        <div class="box-password-change" data-aos="zoom-in" data-aos-duration="1000">
                            <h1 style="text-align: center;">Coming Soon.</h1>
                            <br>
                            <br>
                            <img width="600" height="300" src="{% static 'landing_page/images/passwordchange.svg' %}">
                            <h4>Back to <a href="{% url 'dashboard:dashboard' %}">Home</a></h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>

    <!-- AOS -->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>

</html>
{% endblock %}

dashboard/templates/dashboard/profile.html
{% extends 'dashboard/basedashboard.html' %} {% load static %} {% block content %} {% if user.is_authenticated %}

<section class="personal-information">
    <div class="loader_bg">
        <div class="loader"></div>
    </div>
    {% include 'dashboard/messages.html' %}
    <div class="container">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="box-profile1" data-aos="fade-right" data-aos-duration="1000">
                        <h3 style="text-align: center; margin-top:10px;"><strong>{{ user.first_name }} {{ user.last_name }}</strong></h3>
                        <hr>
                        <div class="personal-info">
                            <p><i class="fas fa-at fa-lg"></i>&nbsp; {{ user.username }}</p>
                            <p><i class="far fa-envelope fa-lg"></i>&nbsp; {{ user.email }}</p>
                            <p><i class="fas fa-university fa-lg"></i>&nbsp;{{ user.userprofile.company_name }}</p>
                        </div>
                        <div class="edit-profile-button">
                            <a href="{% url 'accounts:personal' request.user.id %}" class="btn btn-primary w-100" style="margin-bottom: 20px;">Edit Profile</a>
                        </div>
                        <div class="alert alert-info alert-dismissible fade show" role="alert">
                            Get our latest hints and tips for processing your data in <a href="{% url 'landing_page:tutorial' %}"><strong>Tutorials</strong></a>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>

                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="box-profile2" data-aos="fade-left" data-aos-duration="1000">
                        <div class="profile-redirect">
                            <img width="60%" height="auto" src="{% static 'landing_page/images/try.svg' %}">
                        </div>
                        <div class="dashboard-button" style="transform:translate">
                            <h4>Try <span style="color:#4460EF">eddies</span> dashboard-analytics application right now!</h4>
                            <br>
                            <a href="https://analytics-mvp.herokuapp.com/" target="_blank" class="btn btn-dark" style="margin-bottom: 20px;">Eddies Analytics</a>
                        </div>
                    </div>
                </div>
            </div>
</section>
<!-- <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script> -->


{% else %} Your session has ended, please Login again. <a href="{% url 'accounts:login' %}"> Login </a> {% endif %} {% endblock %}

dashboard/templates/dashboard/validation.html
{% extends 'dashboard/baseproduct.html' %} {% load static %} {% block content %}{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Success - Eddies</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'landing_page/images/eddieslogo.png' %}">
    <!-- AOS -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
</head>

<body style="background: #efeff0;">
    <section id="float-form">
        <div class="container">
            <div class="box-float">
                <div class="row">
                    <div class="col-md-12">
                        <div class="box-password-change" data-aos="zoom-in" data-aos-duration="1000">
                            <h1 style="text-align: center;">Coming Soon.</h1>
                            <br>
                            <br>
                            <img width="600" height="300" src="{% static 'landing_page/images/passwordchange.svg' %}">
                            <h4>Back to <a href="{% url 'dashboard:dashboard' %}">Home</a></h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>

    <!-- AOS -->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>

</html>
{% endblock %}

dashboard/templates/dashboard/visualization.html
{% extends 'dashboard/baseproduct.html' %} {% load static %} {% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Success - Eddies</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'landing_page/images/eddieslogo.png' %}">
    <!-- AOS -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
</head>

<body style="background: #efeff0;">
    <section id="float-form">
        <div class="container">
            <div class="box-float">
                <div class="row">
                    <div class="col-md-12">
                        <div class="box-password-change" data-aos="zoom-in" data-aos-duration="1000">
                            <h1 style="text-align: center;">Coming Soon.</h1>
                            <br>
                            <br>
                            <img width="600" height="300" src="{% static 'landing_page/images/passwordchange.svg' %}">
                            <h4>Back to <a href="{% url 'dashboard:dashboard' %}">Home</a></h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>

    <!-- AOS -->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
</body>

</html>
{% endblock %}