accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import accviews
from django.urls import reverse_lazy

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    path('signup/', accviews.SignUp.as_view(), name='signup'),
    path('<int:pk>/personal/', accviews.personal, name='personal'),
    path('<int:pk>/edit_accounts/', accviews.edit_account, name='edit-account'),
    
    path('<int:pk>/change_password/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change_form.html',success_url=reverse_lazy('accounts:change-password-done')), name='change-password'),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), name='change-password-done'),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_form.html',success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_complete'),

    # path('reset_password/', auth_views.PasswordResetView.as_view(), name='reset_password'),
    # path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

dashboard/urls.py
from django.urls import path
from .dashboardviews import dashboard, overview, preprocessing, processing, validation, visualization, profile, edit_profile

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('<int:pk>/profile/',profile,  name='profile'),
    path('<int:pk>/edit_profile/',edit_profile,  name='edit_profile'),  
    path('overview/',overview,  name='overview'),
    path('preprocessing/',preprocessing,  name='preprocessing'),
    path('processing/',processing,  name='processing'),
    path('validation/',validation,  name='validation'),
    path('visualization/',visualization,  name='visualization'),


    # path('<int:pk>/update/',UserUpdateView.as_view(template_name='dashboard/user_update.html'), name='user_update'),
    # path('files/upload/', dashboardviews.file_upload,  name='file_upload'),
    # path('files/upload/<int:pk>', dashboardviews.delete_file, name='delete_file'),
    
]

landing_page/urls.py
from django.urls import path
from .views import tutorial, product, contact, landing_page, aboutus, newsletter, privacy, terms

app_name = 'landing_page'

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('product/', product, name='product'),
    path('contact/', contact, name='contact'),
    path('about-us/', aboutus, name='about-us'),
    path('tutorials/', tutorial, name='tutorial' ),
    path('privacy_policy/', privacy, name='privacy-policy' ),
    path('terms_of_service/', terms, name='terms-of-service' ),
    # path('news_letter/', newsletter, name='news-letter' ),
    

]

mvp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from landing_page import views
from landing_page.views import HomePage
from accounts import accviews


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomePage,name='home'),
    path('landing_page/', include('landing_page.urls', namespace='landing_page')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eddies</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'landing_page/images/eddieslogo.png' %}">
    <!-- AOS -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'landing_page/css/landingpage.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-9Q0W7MRVN0"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-9Q0W7MRVN0');
    </script>
    <!-- Slider -->
</head>

<body style="background-image:url({% static 'landing_page/images/bg.png' %});">
    <!--- Navigation Bar -->
    <section id="Navbar">
        <nav class="navbar navbar-expand-lg bgcolor navbar-custom">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'landing_page/images/eddieslogo.jpg' %}" alt="logo picture" width="180px" height="auto"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-bars"></i>
                    </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav testi">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'home' %}#">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" aria-haspopup="true">
                              Product
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item drop" href="{% url 'landing_page:product' %}"><img width="75" height="40" src="{% static 'landing_page/images/overview.svg' %}">Eddies Analytics</a>
                            </div>
                        </li>
                        <!-- <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">
                              Tutorials
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item drop" href="{% url 'landing_page:tutorial' %}"><img width="75" height="40" src="{% static 'landing_page/images/article.svg' %}">Articles</a>
                                <a class="dropdown-item drop" href="{% url 'landing_page:tutorial' %}"><img width="75" height="40" src="{% static 'landing_page/images/video.svg' %}">Videos</a>
                            </div>
                        </li> -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">
                              Company
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item drop" href="{% url 'landing_page:about-us' %}"><img width="75" height="40" src="{% static 'landing_page/images/abouteddies.svg' %}">About Eddies</a>
                                <a class="dropdown-item drop" href="{% url 'landing_page:contact' %}"><img width="75" height="40" src="{% static 'landing_page/images/contact.svg' %}">Contact Us</a>
                            </div>
                        </li>
                    </ul>

                    <!-- {% if user.is_authenticated %}
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mynavbar">
                            <a class="nav-link" href="{% url  'dashboard:profile' request.user.id %}">Hello <span style="color:#4460EF;">{{ user.username }} </span>!</a>
                        </li>
                        <li class="nav-item mynavbar">
                            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                    </ul>
                    {% else %}
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mynavbar">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                        </li>
                        <li class="nav-item ">
                            <a class="btnnav" href="{% url 'accounts:signup' %}"><button type="button">Sign Up</button></a>
                        </li>
                    </ul> -->
                    <!-- {% endif %} -->
                </div>
            </div>
        </nav>
    </section>


    {% block content %} {% endblock %}



    <!--- Bottom headline  -->

    <section id="bhead">
        <div class="container">
            <div class="row">
                <div class="col-md-12" style="padding-bottom:60px;" data-aos="zoom-in" data-aos-duration="1000">
                    <div class="highlights">
                        <h1 style="font-size: 4vw;">Start with easy and interactive data processing by eddies!</h1>
                    </div>
                    <!-- <a href="{% url 'accounts:login' %}"><button class="btn-footer">Get Started</button></a> -->
                </div>
            </div>
        </div>
        <div class="wavy1">
            <a href="#">
                <img src="{% static 'landing_page/images/1.png' %}" style="width: 100%;" alt="">
            </a>
        </div>
    </section>


    <!--- Footer  -->

    <section id="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-6 footers" style="border-bottom:2px solid black;">
                    <ul>
                        <li>
                            <img src="{% static 'landing_page/images/eddieslogo.jpg' %}" alt="logo picture" width="200px" height="auto">
                        </li>
                        <li>
                            <a href="{% url 'landing_page:about-us' %}">
                                <h7>About Us</h7>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'landing_page:contact' %}">
                                <h7>Contact</h7>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-6 footers" style="border-bottom:2px solid black;">
                    <ul class=social-menu>
                        <li><a href="#"><i class="fab fa-linkedin fa-2x"></i></a></li>
                        <li><a href="https://www.instagram.com/ai.eddies/" target="_blank"><i class="fab fa-instagram fa-2x"></i></a></li>
                        <li><a href="{% url 'landing_page:contact' %}"><i class="far fa-envelope fa-2x"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>

        <section id="footer2">
            <div class="container">
                <div class="row">
                    <div class="col-md-12" style="height: 10%;">
                        <ul>
                            <div>
                                <h6><a href="https://iconscout.com/illustrations/concept" target="_blank" style="color: black">Concept of data analysis and maintenance Illustration</a> by <a href="https://iconscout.com/contributors/woobrodesign">WOOBRO DESIGN</a>                                    on <a href="https://iconscout.com">Iconscout</a></h6>
                                <h6>Copyright <i class="far fa-copyright fa-sm"></i> 2020 eddies, inc. All right reserved</i> | Icons made by <a href="https://www.flaticon.com/authors/eucalyp" title="Eucalyp">Eucalyp</a> from <a href="https://www.flaticon.com/"
                                        title="Flaticon">www.flaticon.com</a> | Powered by <img src="{% static 'landing_page/images/django.png' %}" style="width:80px; height:auto;"> </h6>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
        <!-- JS -->
        <script src="{% static 'landing_page/js/jquery.min.js' %}"></script>
        <script src="{% static 'landing_page/js/bootstrap.bundle.min.js' %}"></script>
        <script>
            $(window).scroll(function() {
                $('nav').toggleClass('scrolled', $(this).scrollTop() > 200);
            });
            setTimeout(function() {
                if ($('#msg').length > 0) {
                    $('#msg').remove();
                }
            }, 6000);
            setTimeout(function() {
                $('.loader_bg').fadeToggle();
            }, 500);
            $(document).ready(function() {
                $('ul.navbar-nav > li')
                    .click(function(e) {
                        $('ul.navbar-nav > li')
                            .removeClass('active');
                        $(this).addClass('active');
                    });
            });
        </script>
        <!-- AOS -->
        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
        <script>
            AOS.init();
        </script>

</body>

</html>

templates/index.html
{% extends 'base.html' %} {% load static %}{% load bootstrap5 %} {% block content %}
<!--- Killer Headline -->

<div class="loader_bg">
    <div class="loader"></div>
</div>
{% include 'dashboard/messages.html' %}
<section id="killerheadbanner">
    <div class="row">
        <div class="col-md-6">
            <div class="killer-text" data-aos="fade-in" data-aos-duration="1000">

                <h1>Powering your ocean data</h1>
                <br>
                <h4>Transform your work and research through collaboration <br> and advanced data analytics in the cloud.</h4>
                <br>

                <!-- <a href="#">
                    <button id="demobutton">Demo</button>
                </a> -->
                <a href="{% url 'landing_page:about-us' %}">
                    <button id="startbutton">Try for free</button>
                </a>
            </div>
        </div>

        <div class="col-md-6">
            <div class="killer-image" data-aos="zoom-in" data-aos-duration="1000">
                <img width="90%" height="auto" src="{% static 'landing_page/images/killerhead.svg' %}">
            </div>
        </div>
    </div>
</section>

<!--- title -->
<section id="firsttitle" data-aos="fade-up" data-aos-duration="1000">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="textareaimage1">
                    <img width="75%" height="auto" src="{% static 'landing_page/images/fast.svg' %}" alt="picture crash">
                </div>
            </div>
            <div class="col-md-6">
                <div class="textarea1">
                    <h1>
                        Accelerate your ocean research with Eddies.
                    </h1>
                    <br>
                    <h4>Data processing and visualization are the essential parts of ocean research, but these parts is being hindered by time-consuming process of difficult and complex coding.</h4>
                    <h4>Eddies is a web-based ocean data analytics platform that will help you preparing to visualizing your data.</h4>
                </div>

            </div>
        </div>
    </div>
</section>

<!--- Feature 1 -->
<section id="f1">
    <div class="container" data-aos="fade-up" data-aos-duration="1000">
        <div class="row">
            <div class="col-md-6">
                <div class="textarea2">
                    <h1>Focus on your analysis, not on the code.
                    </h1>
                    <br>
                    <h4>Technical tasks like coding can be complicated and time-consuming for your research. Eddies can help you to solve such problems by providing an easy-to-use data analytics tool. Processing data and visualization can be done in minutes.
                        So, you can focus on your analysis.
                    </h4>
                </div>
            </div>
            <div class="col-md-6">
                <div class="textareaimage1">
                    <img width="80%" height="auto" src="{% static 'landing_page/images/focus.svg' %}" alt="picture crash">
                </div>
            </div>
        </div>
    </div>
    </div>
</section>



<!--- Feature 2 -->
<section id="f2">
    <div class="container" data-aos="zoom-in" data-aos-duration="1000">
        <div class="row">
            <div class="col-md-6">
                <div class="textarea2">
                    <h1>All-in-one cloud solution.
                    </h1>
                    <br>
                    <h4>Dealing with multiple software might slow down your work. We provide cloud-based data analytic tools that enable you to work in one integrated platform.
                    </h4>
                    <p></p>
                </div>
            </div>
            <div class="col-md-6">
                <div class="textareaimage1">
                    <img width="80%" height="auto" src="{% static 'landing_page/images/allinone.svg' %}" alt="picture crash">
                </div>
            </div>

        </div>
    </div>
</section>




<!--- About Big Data / Ocean Data Processing  -->
<section id="aboutdata">
    <div class="container">
        <h1 class="title text-center">What exactly we need ?</h1>
        <div class="row upperrow" data-aos="fade-up" data-aos-duration="1000">
            <div class="col-md-4 testimonials">
                <p>Memory is often the main problem in big data processing. It takes a large enough memory to be able to perform data processing properly. It would be very good if we don't need to think about the memory capacity of the devices we have.</p>
                <i class="fas fa-user-cog"></i>
                <h7 style="font-size:2.1vmin;"><strong>Professionals - Tech. Support Engineer</strong></h7>
            </div>
            <div class="col-md-4 testimonials">
                <p>The display form of the results of data processing is a very important factor for data analysis, so that the purposes and objectives of data processing can be easily understood by cross-sectors or companies.</p>
                <i class="fas fa-user-cog"></i>
                <h7 style="font-size:2.1vmin;"><strong>Professionals - Metocean Data Analyst</strong></h7>
            </div>
            <div class="col-md-4 testimonials">
                <p>
                    Data identification and processing cannot be separated from the many parameters in the sea itself. The variation and level of difficulty in data processing is often one of the obstacles in the processing stage. Can we get the data results without encountering
                    this problem?</p>
                <i class="fas fa-user-graduate fa-sm"></i>
                <h7 style="font-size:2.1vmin;"><strong>Academics - Researcher</strong></h7>
            </div>

        </div>
        <div class="row bottomrow" data-aos="fade-up" data-aos-duration="1000">
            <div class="col-md-4 testimonials">
                <p>The things that are troublesome when I process oceanographic data are: First, the data is large because the data is four dimensions; second, PCs sometimes have to be able to perform statistical calculations with big data; third, sometimes
                    you cannot arbitrarily choose a visualization method, because it can cause the results of data interpretation to be inconsistent with the theory.
                </p>
                <i class="fas fa-user-graduate fa-sm"></i>
                <h7 style="font-size:2.1vmin;"><strong>Professionals - Oceanographer</strong></h7>
            </div>
            <div class="col-md-4 testimonials">
                <p>There is a lot of blank data. So, we have to use interpolation method, but it is not always effective and risky to fill the blank data. For time series data, if the data is too long, there must be a script adjustment for processing the
                    data.
                </p>
                <i class="fas fa-user-cog"></i>
                <h7 style="font-size:2.1vmin;"><strong>Academics - Oceanography Lecturer</strong></h7>
            </div>
            <div class="col-md-4 testimonials">
                <p>I have difficulty tidying up data and extracting lots of raw data. For example, when processing data, the data that appears in one hour can be up to five data. In fact, the data required is only one data per hour. In addition, data reorganization
                    is required due to the different file formats. for example, when data is transferred from Matlab output to MS Excel, the data representation is different from the initial data.</p>
                <i class="fas fa-user-graduate fa-sm"></i>
                <h7 style="font-size:2.1vmin;"><strong>Student - Undergraduate Program</strong></h7>
            </div>
        </div>
    </div>
</section>


<!--- Feature 3 -->
<section id="f3">
    <div class="container">
        <div class="row">
            <div class="col-md-12" data-aos="zoom-in" data-aos-duration="1000">
                <div class="textarea3">
                    <h1>Understand your data faster.</h1>
                    <br>
                    <img width="40%" height="auto" src="{% static 'landing_page/images/understanddata.svg' %}" alt="picture crash">
                    <a href="{% url 'landing_page:product' %}"><button type="button" id="learnbutton">Learn More</button> </a>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>
<section id="newsletter">
    <div class="container">
        <div class="newsletter1" data-aos="fade-up" data-aos-duration="1000">
            <h1 style="font-size:4vw;">Request for <span style="color:#4460EF">Early Adopters</span></h1>
            <h4 style="font-weight: 200;">Get opportunity to try our Eddies early stage product for <strong>free</strong>.</h4>
            <div class="newsletter">
                <form method="POST">
                    {% csrf_token %} {% bootstrap_form newsform %}
                    <br>
                    <input type="submit" class='btn btn-primary btn-lg w-100' value="Request">
                </form>
            </div>
        </div>
    </div>
</section>




{% endblock %}